### ISSUE TITLE
Can this be updated to support ReSharper 2024.2.6

### ISSUE THREAD

**Issue by sjtuross** [LocalizationTools/LocalizationTools.ReSharper#1]
It looks like this plugin doesn't show up in ReSharper Extensions in 2024.2.6. It does in 2023.3.6.

**Comment by softworkz** [comment]
Yes, they are always changing their APIs and I haven't upated the plugin yet.

**Comment by softworkz** [comment]
A new version is in validation now, it's said to take two business days, so it should be available by Tuesday

**Comment by sjtuross** [comment]
It works great. Thank you sir.

**Comment by softworkz** [comment]
I have suggested R# to take my extension code and integrate it into R#, maybe you can vote for it? https://youtrack.jetbrains.com/issue/RSRP-492179/Consider-Integration-of-my-R-Plugin-Code-for-Attribute-Localization
